#!/usr/bin/env python

import zktools

if __name__ == "__main__":
    args = zktools.args('Copies ZK node', dest={'default': None, 'help':'Destination to copy node to'})
    try:
        with zktools.kazoo(args.host) as zk:
            zktools.copy(zk, args.path, args.dest)
            zktools.ok()
    except Exception as e:
        print e
        zktools.fail()
