#!/usr/bin/env python

import zktools

if __name__ == "__main__":
    args = zktools.args("Lists nodes by ZK path")
    try:
        with zktools.kazoo(args.host) as zk:
            print "\n".join(zktools.ls(zk, args.path))
            zktools.ok()
    except Exception as e:
        print e
        zktools.fail()
