#!/usr/bin/env python

import zktools

if __name__ == "__main__":
    args = zktools.args('Removes ZK node by its path')
    try:
        with zktools.kazoo(args.host) as zk:
            zktools.remove(zk, args.path)
    except Exception as e:
        print e
        zktools.fail()
